/**
 * Execution Loop — The core agent loop.
 *
 * The universal execution pattern:
 *
 *   event → input guard → context → brain → guard → dispatch:
 *     terminal (respond/escalate/clarify/delegate) → sanitize → deliver → done
 *     use_tool → validate → dedup → execute → record → plan advance → loop
 *     approval needed → pause task → notify → done (resume via approval_callback)
 *
 * Production features:
 *   - Task resumption: tool_callback/user_message/approval_callback resume existing tasks
 *   - Durable approval: async approval flow with waiting_approval status
 *   - AbortSignal: kill-task can interrupt in-flight tool calls
 *   - Distributed dedup: ToolAdapter.checkIdempotency() for cross-worker safety
 *   - Cost tracking: costExtractor hook for brain-reported LLM costs
 *   - Evidence chain: ResponseEvidence + ActionReceipt on terminal outcomes
 *   - Output sanitization: strips secrets/PII before delivery
 *   - Input guard: prompt injection defense
 *   - Conversation repair: user-friendly error message on fatal failures
 *   - Plan acknowledgment: onPlanCreated hook for multi-step plan notifications
 *   - Run state durability: optional persist/load via MemoryAdapter
 *   - Structured response format: pass-through for rich channel rendering
 *   - Tool call budget: maxToolCallsPerTask guard
 */

import type {
  AgentConfig,
  Brain,
  BrainPayload,
  BrainRunInput,
  LoopOutcome,
  RunState,
  StepResult,
  TaskState,
  AgentEvent,
  ResponseEvidence,
  ActionReceipt,
  ResponseFormat,
  ToolResult,
} from "./types.js";
import { STANDARD_ACTIONS } from "./types.js";
import type { MemoryAdapter } from "../adapters/memory.js";
import type { ToolAdapter } from "../adapters/tools.js";
import type { DeliveryAdapter } from "../adapters/delivery.js";
import type { ControlBusAdapter } from "../adapters/control-bus.js";
import { checkGuards, hasHardBlock } from "./guards.js";
import { buildContext } from "./context.js";
import {
  createPlan,
  advancePlanStep,
  failPlanStep,
  canReplan,
  clearPlan,
} from "./planner.js";
import { checkDedup } from "./tool-dedup.js";
import { sanitizeOutput } from "./sanitize.js";
import { guardInput } from "./input-guard.js";

export interface LoopDeps {
  brain: Brain;
  memory: MemoryAdapter;
  tools: ToolAdapter;
  delivery: DeliveryAdapter;
  config: AgentConfig;
  /** Optional: control bus for runtime operability (pause/kill/disable) */
  controlBus?: ControlBusAdapter;
  /** Optional: tenant ID for control bus checks */
  tenantId?: string;
  /** Optional: called on every iteration for observability */
  onIteration?: (state: RunState, step: StepResult) => void;
  /** Optional: called when a guard fires */
  onGuard?: (signal: import("./types.js").GuardSignal) => void;
  /** Optional: custom history compaction hook (passed through to buildContext) */
  compactHistory?: (
    messages: import("./types.js").Message[],
  ) => Promise<Array<{ role: "user" | "assistant"; content: string }>>;
  /**
   * Optional: extract cost in USD from a brain payload.
   * Called after every brain.run() to track cumulative cost.
   * If not provided, cost tracking remains at 0.
   */
  costExtractor?: (payload: BrainPayload) => number;
  /**
   * Optional: called when a multi-step plan is created.
   * Use to send acknowledge messages ("Let me check for you...").
   * Not called for single-step plans (suppress ack for single-step plans).
   */
  onPlanCreated?: (
    sessionId: string,
    plan: import("./types.js").TaskPlan,
  ) => Promise<void>;
  /**
   * Optional: called on fatal error to produce a user-friendly recovery message.
   * If provided, the repair message is delivered to the user before returning the error.
   * sends "Sorry, something went wrong..."
   */
  onFatalError?: (sessionId: string, error: string) => Promise<string>;
  /**
   * Optional: called when input injection is detected.
   * Use for logging/alerting. The input is still processed (stripped) unless
   * the hook returns a LoopOutcome to short-circuit.
   */
  onInjectionDetected?: (
    sessionId: string,
    patterns: string[],
  ) => Promise<LoopOutcome | null | undefined>;
  /**
   * Optional: hints from the evolving layer (MemoryEvolvingAdapter in assist mode).
   * Injected into system context as "Past approaches" to guide the brain.
   * Populated by agent.ts from EvolvingAdapter.preReason() — not set by callers directly.
   */
  evolvingHints?: string[];
  /**
   * Optional: pre-rendered equipment block for injection into the system prompt.
   * Generated by renderEquipmentBlock(def.equipment) in cli.ts and passed through.
   * Tells the LLM explicitly which external systems it can reach and at what access level.
   */
  equipmentBlock?: string;
  /**
   * Optional: vector knowledge base adapter.
   * When provided, the top-K most relevant KB chunks are injected into the brain
   * prompt as [knowledge] context on every iteration.
   * Set via createAgent({ knowledge: QdrantKnowledgeAdapter.create(...) })
   */
  knowledge?: import("../adapters/knowledge.js").KnowledgeAdapter;
  /**
   * Optional: streaming text delta callback.
   * When set AND the brain implements stream(), the loop calls stream() instead
   * of run() and invokes this callback for every incremental text token.
   * Used by the HTTP layer to forward SSE chunks to the client in real time.
   */
  onTextDelta?: (delta: string) => void;
}

/**
 * Execute a single agent event through the brain loop.
 *
 * This is the heart of the agent — the equivalent of the production execution engine.
 */
export async function executeEvent(
  event: AgentEvent,
  deps: LoopDeps,
  /** Optional override for session ID (used by createAgent to pass stable cron IDs) */
  sessionIdOverride?: string,
): Promise<LoopOutcome> {
  const sessionId =
    sessionIdOverride ??
    ("sessionId" in event ? event.sessionId : `cron-${Date.now()}`);

  // ─── Input Guard: Prompt Injection Defense ───────────────
  let text: string;
  if (event.type === "user_message") {
    const guardResult = guardInput(event.text);
    text = guardResult.text;
    if (guardResult.injectionDetected && deps.onInjectionDetected) {
      const shortCircuit = await deps.onInjectionDetected(
        sessionId,
        guardResult.matchedPatterns,
      );
      if (shortCircuit) return shortCircuit;
    }
  } else if (event.type === "tool_callback") {
    text = `Tool result received for task ${event.taskId}`;
  } else if (event.type === "approval_callback") {
    text = `Approval ${event.approved ? "granted" : "denied"} for task ${event.taskId}`;
  } else if (event.type === "webhook") {
    text = `Webhook from ${event.source}`;
  } else {
    text = `Scheduled task: ${event.taskType}`;
  }
  const modality =
    event.type === "user_message" ? event.modality : ("text" as const);

  // ─── Task Resumption ─────────────────────────────────────
  // For tool_callback: resume the referenced task
  // For approval_callback: resume the referenced task
  // For user_message: check for an active waiting task to resume
  // Otherwise: create a new task
  let task: TaskState;
  let resumed = false;

  if (event.type === "tool_callback") {
    const existing = await deps.memory.getTask(event.taskId);
    if (
      existing &&
      (existing.status === "waiting_tool" || existing.status === "running")
    ) {
      task = existing;
      task.status = "running";
      await deps.memory.updateTaskStatus(task.taskId, "running");
      resumed = true;
    } else {
      // Stale callback — create fresh task
      task = createNewTask(sessionId);
      await deps.memory.saveTask(task);
    }
  } else if (event.type === "approval_callback") {
    const existing = await deps.memory.getTask(event.taskId);
    if (existing && existing.status === "waiting_approval") {
      if (!event.approved) {
        // Approval denied — fail the tool, let brain replan
        task = existing;
        task.status = "running";
        await deps.memory.updateTaskStatus(task.taskId, "running");
        resumed = true;
        // Inject denial as a tool result so brain knows
      } else {
        task = existing;
        task.status = "running";
        await deps.memory.updateTaskStatus(task.taskId, "running");
        resumed = true;
      }
    } else {
      // Stale approval — ignore
      return {
        type: "error",
        error: `No waiting_approval task found for ${event.taskId}`,
      };
    }
  } else if (event.type === "user_message" && deps.memory.getActiveTask) {
    const active = await deps.memory.getActiveTask(sessionId);
    if (active && active.status === "waiting_clarification") {
      task = active;
      task.status = "running";
      await deps.memory.updateTaskStatus(task.taskId, "running");
      resumed = true;
    } else {
      task = createNewTask(sessionId);
      await deps.memory.saveTask(task);
    }
  } else {
    task = createNewTask(sessionId);
    await deps.memory.saveTask(task);
  }

  const taskId = task.taskId;

  // Record user message
  await deps.memory.addMessage(sessionId, {
    role: "user",
    content: text,
    timestamp: new Date().toISOString(),
  });

  // Initialize run state (carry forward tool call count if resumed)
  // Try to load durable run state if available (e.g. Redis with TTL)
  const priorToolCalls = resumed
    ? task.steps.filter((s) => s.toolResult !== null).length
    : 0;
  let state: RunState;
  if (resumed && deps.memory.loadRunState) {
    const savedState = await deps.memory.loadRunState(taskId);
    state = savedState ?? {
      iteration: 0,
      totalCostUsd: resumed ? task.totalCostUsd : 0,
      startTime: Date.now(),
      replanCount: resumed ? (task.plan?.replanCount ?? 0) : 0,
      toolCallCount: priorToolCalls,
      recentSteps: resumed ? task.steps.slice(-10) : [],
    };
  } else {
    state = {
      iteration: 0,
      totalCostUsd: resumed ? task.totalCostUsd : 0,
      startTime: Date.now(),
      replanCount: resumed ? (task.plan?.replanCount ?? 0) : 0,
      toolCallCount: priorToolCalls,
      recentSteps: resumed ? task.steps.slice(-10) : [],
    };
  }

  let lastToolResult: ToolResult | undefined;
  let lastPayload: BrainPayload | undefined;

  // For tool_callback, seed the last tool result from the event
  if (event.type === "tool_callback") {
    lastToolResult = event.result;
  }

  // For approval_callback with denial, seed a synthetic failed tool result
  if (event.type === "approval_callback" && !event.approved) {
    let lastToolStep: StepResult | undefined;
    for (let i = task.steps.length - 1; i >= 0; i--) {
      if (task.steps[i].toolName) {
        lastToolStep = task.steps[i];
        break;
      }
    }
    if (lastToolStep) {
      lastToolResult = {
        tool: lastToolStep.toolName!,
        status: "failed",
        result: {
          reason: `Approval denied${event.decidedBy ? ` by ${event.decidedBy}` : ""}`,
        },
      };
    }
  }

  // AbortController for in-flight tool calls
  let toolAbortController: AbortController | null =
    null as AbortController | null;

  // ─── The Loop ────────────────────────────────────────────
  while (state.iteration < deps.config.maxIterations) {
    // ─── Control Bus: Abort/Pause Check ────────────────────
    if (deps.controlBus) {
      const killReason = await deps.controlBus.isTaskKilled(taskId);
      if (killReason) {
        // Abort any in-flight tool call
        toolAbortController?.abort();
        deps.onGuard?.({ type: "aborted", taskId, reason: killReason });
        await finishTask(task, "aborted", deps);
        return { type: "aborted", taskId, reason: killReason };
      }
      if (deps.tenantId) {
        const pauseReason = await deps.controlBus.isTenantPaused(deps.tenantId);
        if (pauseReason) {
          toolAbortController?.abort();
          deps.onGuard?.({
            type: "aborted",
            taskId,
            reason: `Tenant paused: ${pauseReason}`,
          });
          await finishTask(task, "aborted", deps);
          return {
            type: "aborted",
            taskId,
            reason: `Tenant paused: ${pauseReason}`,
          };
        }
      }
    }

    // Send typing indicator if available
    await deps.delivery.sendTyping?.(sessionId);

    // Build context for brain
    const brainInput = await buildContext({
      sessionId,
      text,
      modality,
      memory: deps.memory,
      tools: deps.tools,
      state,
      task,
      lastToolResult,
      compactHistory: deps.compactHistory,
      evolvingHints: deps.evolvingHints,
      equipmentBlock: deps.equipmentBlock,
      knowledge: deps.knowledge,
    });

    // ─── Call Brain (with error handling) ──────────────────
    let payload: BrainPayload;
    const startMs = Date.now();
    try {
      // Use streaming when the brain supports it AND the caller wants deltas
      if (deps.onTextDelta && deps.brain.stream) {
        const stream = deps.brain.stream(brainInput);
        let done: BrainPayload | undefined;
        for await (const chunk of stream) {
          if (chunk.type === "delta") {
            deps.onTextDelta(chunk.text);
          } else if (chunk.type === "done") {
            done = chunk.payload;
            break;
          }
        }
        if (!done) throw new Error("Brain stream ended without a done chunk");
        payload = done;
      } else {
        payload = await deps.brain.run(brainInput);
      }
    } catch (err) {
      // Brain call failed — failTask lifecycle instead of unhandled crash
      const error = err instanceof Error ? err.message : String(err);
      await finishTask(task, "failed", deps, error);
      // Conversation repair: send user-friendly error message (conversation repair)
      if (deps.onFatalError) {
        try {
          const repairMsg = await deps.onFatalError(sessionId, error);
          await deps.delivery.send(sessionId, {
            type: "response",
            text: repairMsg,
            language: "en",
            payload: {} as BrainPayload,
          });
        } catch {
          // repair itself failed — don't crash
        }
      }
      return {
        type: "error",
        error: `Brain call failed: ${error}`,
      };
    }
    const latencyMs = Date.now() - startMs;
    lastPayload = payload;

    // ─── Cost Tracking ────────────────────────────────────
    if (deps.costExtractor) {
      const iterationCost = deps.costExtractor(payload);
      state.totalCostUsd += iterationCost;
      task.totalCostUsd = state.totalCostUsd;
    }

    // Extract brain's decision from orchestration layer
    const orch = payload.orchestration;
    if (!orch) {
      await finishTask(
        task,
        "failed",
        deps,
        "Brain returned no orchestration output",
      );
      return {
        type: "error",
        error: "Brain returned no orchestration output",
        payload,
      };
    }

    const action = orch.action;
    const confidence = orch.confidence;
    const toolName = orch.tool_name ?? null;
    const toolParams = orch.tool_params ?? null;
    const reasoning = orch.reasoning ?? "";

    // If brain returned a plan on first call, track it
    if (orch.plan && orch.plan.length > 0 && !task.plan) {
      task.plan = createPlan(orch.plan, reasoning);
      await deps.memory.saveTask(task);
      // Acknowledge multi-step plans (suppress for single-step)
      if (task.plan.steps.length > 1 && deps.onPlanCreated) {
        await deps.onPlanCreated(sessionId, task.plan);
      }
    }

    // Persist run state for durability (e.g. Redis TTL extension)
    if (deps.memory.saveRunState) {
      await deps.memory.saveRunState(taskId, state);
    }

    // ─── Guard Check ─────────────────────────────────────
    const signals = checkGuards(
      state,
      deps.config,
      action,
      confidence,
      toolName,
    );
    for (const signal of signals) {
      deps.onGuard?.(signal);
    }

    if (hasHardBlock(signals)) {
      // Check if it's a confidence gate → convert to clarification
      const confidenceBlock = signals.find((s) => s.type === "confidence_low");
      if (confidenceBlock) {
        const clarifyText =
          payload.generation?.response_text ??
          payload.final_output?.text ??
          "Could you provide more details?";
        await finishTask(task, "waiting_clarification", deps);
        return {
          type: "clarification",
          question: clarifyText,
          payload,
          taskId,
        };
      }

      // Budget/iteration limit → force respond with whatever we have
      const rawText =
        payload.final_output?.text ??
        payload.generation?.response_text ??
        "I was unable to complete this task within the allowed limits.";
      const sanitized = sanitizeOutput(rawText);
      const { evidence, receipts } = buildEvidence(task.steps);
      await finishTask(task, "completed", deps);
      return {
        type: "response",
        text: sanitized.text,
        textAr: payload.generation?.response_text_ar,
        language: payload.final_output?.language ?? "en",
        payload,
        evidence: evidence.length > 0 ? evidence : undefined,
        receipts: receipts.length > 0 ? receipts : undefined,
        responseFormat: extractResponseFormat(payload),
      };
    }

    // ─── Terminal Actions ─────────────────────────────────
    if (action === STANDARD_ACTIONS.RESPOND || action === "complete") {
      const rawText =
        payload.final_output?.text ??
        payload.generation?.response_text ??
        "Done.";
      const sanitized = sanitizeOutput(rawText);

      // Record step
      const step = recordStep(
        state,
        action,
        null,
        null,
        null,
        confidence,
        reasoning,
        latencyMs,
      );
      deps.onIteration?.(state, step);

      // Record assistant message
      await deps.memory.addMessage(sessionId, {
        role: "assistant",
        content: sanitized.text,
        timestamp: new Date().toISOString(),
      });

      const { evidence, receipts } = buildEvidence(task.steps);
      await finishTask(task, "completed", deps);
      return {
        type: "response",
        text: sanitized.text,
        textAr: payload.generation?.response_text_ar,
        language: payload.final_output?.language ?? "en",
        payload,
        evidence: evidence.length > 0 ? evidence : undefined,
        receipts: receipts.length > 0 ? receipts : undefined,
        responseFormat: extractResponseFormat(payload),
      };
    }

    if (action === STANDARD_ACTIONS.ESCALATE) {
      const step = recordStep(
        state,
        action,
        null,
        null,
        null,
        confidence,
        reasoning,
        latencyMs,
      );
      deps.onIteration?.(state, step);
      await finishTask(task, "escalated", deps);
      return { type: "escalated", reason: reasoning, payload };
    }

    if (action === STANDARD_ACTIONS.CLARIFY || action === "ask_clarification") {
      const question =
        payload.generation?.response_text ??
        payload.final_output?.text ??
        "Could you clarify?";
      const step = recordStep(
        state,
        action,
        null,
        null,
        null,
        confidence,
        reasoning,
        latencyMs,
      );
      deps.onIteration?.(state, step);
      await finishTask(task, "waiting_clarification", deps);
      return {
        type: "clarification",
        question,
        questionAr: payload.generation?.response_text_ar,
        payload,
        taskId,
      };
    }

    if (action === STANDARD_ACTIONS.DELEGATE) {
      const step = recordStep(
        state,
        action,
        null,
        null,
        null,
        confidence,
        reasoning,
        latencyMs,
      );
      deps.onIteration?.(state, step);
      await finishTask(task, "completed", deps);
      return {
        type: "delegated",
        targetRole: orch.delegate_to_role ?? "unknown",
        payload,
      };
    }

    // ─── Tool Execution ──────────────────────────────────
    if (action === STANDARD_ACTIONS.USE_TOOL || action === "use_tool") {
      if (!toolName) {
        // Brain said use_tool without specifying which tool — this is a
        // malformed decision. Abort immediately to prevent infinite loops
        // (malformed decision → failTask).
        const step = recordStep(
          state,
          action,
          null,
          null,
          null,
          confidence,
          "INVALID_REASONING: use_tool without tool_name",
          latencyMs,
        );
        deps.onIteration?.(state, step);
        await finishTask(task, "failed", deps, "use_tool without tool_name");
        return {
          type: "error",
          error: "Brain returned use_tool without a valid tool_name",
          payload,
        };
      }

      // Control bus: check if tool is disabled
      if (deps.controlBus) {
        const disableReason = await deps.controlBus.isToolDisabled(toolName);
        if (disableReason) {
          const step = recordStep(
            state,
            action,
            toolName,
            toolParams,
            {
              tool: toolName,
              status: "failed",
              result: { reason: `Tool disabled: ${disableReason}` },
            },
            confidence,
            `Tool disabled: ${disableReason}`,
            latencyMs,
          );
          deps.onIteration?.(state, step);
          state.iteration++;
          lastToolResult = step.toolResult!;
          continue;
        }
      }

      // Rate limit check
      if (deps.tools.checkRateLimit) {
        const retryAfterMs = deps.tools.checkRateLimit(toolName);
        if (retryAfterMs > 0) {
          deps.onGuard?.({ type: "rate_limited", toolName, retryAfterMs });
          const step = recordStep(
            state,
            action,
            toolName,
            toolParams,
            {
              tool: toolName,
              status: "failed",
              result: { reason: "Rate limited", retryAfterMs },
            },
            confidence,
            `Rate limited: retry after ${retryAfterMs}ms`,
            latencyMs,
          );
          deps.onIteration?.(state, step);
          state.iteration++;
          lastToolResult = step.toolResult!;
          continue;
        }
      }

      // ─── Distributed Idempotency Check ─────────────────
      const toolDef = deps.tools.list().find((t) => t.name === toolName);
      if (toolDef?.destructive && deps.tools.checkIdempotency) {
        const cached = await deps.tools.checkIdempotency(
          toolName,
          toolParams ?? {},
        );
        if (cached) {
          const step = recordStep(
            state,
            action,
            toolName,
            toolParams,
            cached,
            confidence,
            "Idempotency: returning distributed cached result",
            latencyMs,
          );
          deps.onIteration?.(state, step);
          lastToolResult = cached;
          state.iteration++;
          state.toolCallCount++;
          continue;
        }
      }

      // In-process dedup (fallback for non-destructive or when no distributed adapter)
      if (deps.config.toolDedup) {
        const dedup = checkDedup(toolName, toolParams ?? {}, state.recentSteps);
        if (dedup.isDuplicate && dedup.cachedResult) {
          const step = recordStep(
            state,
            action,
            toolName,
            toolParams,
            dedup.cachedResult,
            confidence,
            "Dedup: returning cached result",
            latencyMs,
          );
          deps.onIteration?.(state, step);
          lastToolResult = dedup.cachedResult;
          state.iteration++;
          continue;
        }
      }

      // Validate tool if adapter supports it
      if (deps.tools.validate) {
        const validation = deps.tools.validate(toolName, toolParams ?? {});
        if (!validation.valid) {
          const step = recordStep(
            state,
            action,
            toolName,
            toolParams,
            {
              tool: toolName,
              status: "failed",
              result: { errors: validation.errors },
            },
            confidence,
            `Validation failed: ${validation.errors.join(", ")}`,
            latencyMs,
          );
          deps.onIteration?.(state, step);
          state.iteration++;
          lastToolResult = step.toolResult!;
          continue;
        }
      }

      // Check approval if needed (two modes: sync boolean or async "pending")
      if (toolDef?.requiresApproval && deps.delivery.requestApproval) {
        const approvalResult = await deps.delivery.requestApproval(
          sessionId,
          taskId,
          toolName,
          toolParams ?? {},
          reasoning,
        );
        if (approvalResult === "pending") {
          // Durable approval: pause task and wait for approval_callback event
          // Save run state so we can resume after approval decision
          if (deps.memory.saveRunState) {
            await deps.memory.saveRunState(taskId, state);
          }
          await finishTask(task, "waiting_approval", deps);
          return {
            type: "waiting_approval",
            taskId,
            toolName,
            toolParams: toolParams ?? {},
            reasoning,
            payload,
          };
        }
        if (!approvalResult) {
          const step = recordStep(
            state,
            action,
            toolName,
            toolParams,
            {
              tool: toolName,
              status: "failed",
              result: { reason: "Approval denied" },
            },
            confidence,
            "User denied approval",
            latencyMs,
          );
          deps.onIteration?.(state, step);
          state.iteration++;
          lastToolResult = step.toolResult!;
          continue;
        }
      }

      // Extend run state TTL before potentially long tool execution (production pattern)
      if (deps.memory.extendRunStateTTL) {
        await deps.memory.extendRunStateTTL(taskId);
      }

      // Execute the tool with AbortSignal
      toolAbortController = new AbortController();
      const toolStart = Date.now();
      let toolResult: ToolResult;
      try {
        toolResult = await deps.tools.execute(
          toolName,
          toolParams ?? {},
          toolAbortController.signal,
        );
      } catch (err) {
        toolResult = {
          tool: toolName,
          status: "failed",
          result: {
            error: err instanceof Error ? err.message : String(err),
            aborted: toolAbortController.signal.aborted,
          },
        };
      }
      const toolLatency = Date.now() - toolStart;
      toolAbortController = null;

      // Post-execution control bus check (catch kills during tool execution)
      if (deps.controlBus) {
        const killReason = await deps.controlBus.isTaskKilled(taskId);
        if (killReason) {
          deps.onGuard?.({ type: "aborted", taskId, reason: killReason });
          await finishTask(task, "aborted", deps);
          return { type: "aborted", taskId, reason: killReason };
        }
      }

      // Record distributed idempotency for successful destructive calls
      if (
        toolDef?.destructive &&
        toolResult.status === "ok" &&
        deps.tools.recordIdempotency
      ) {
        await deps.tools.recordIdempotency(
          toolName,
          toolParams ?? {},
          toolResult,
        );
      }

      // Record step
      const step = recordStep(
        state,
        action,
        toolName,
        toolParams,
        toolResult,
        confidence,
        reasoning,
        latencyMs + toolLatency,
      );
      // Thread task through loop — push step to in-memory task and save once
      // instead of letting addStep() do a redundant getTask() round-trip.
      task.steps.push(step);
      // Plan management (mutate task.plan in-memory first, then persist together)
      if (toolResult.status === "ok" && task.plan) {
        task.plan = advancePlanStep(task.plan);
      } else if (toolResult.status === "failed" && task.plan) {
        task.plan = failPlanStep(task.plan);
        if (canReplan(task.plan, deps.config.maxReplans)) {
          task.plan = { ...task.plan, replanCount: task.plan.replanCount + 1 };
        } else {
          task.plan = clearPlan();
        }
      }
      await deps.memory.saveTask(task);
      deps.onIteration?.(state, step);
      state.toolCallCount++;

      lastToolResult = toolResult;
      state.iteration++;
      continue;
    }

    // ─── Custom Action ───────────────────────────────────
    // Actions beyond the standard 5 — let the caller handle them
    const step = recordStep(
      state,
      action,
      null,
      null,
      null,
      confidence,
      reasoning,
      latencyMs,
    );
    deps.onIteration?.(state, step);
    await finishTask(task, "completed", deps);
    return { type: "custom", action, payload };
  }

  // Loop exhausted without terminal action
  const rawFallback =
    lastPayload?.final_output?.text ??
    lastPayload?.generation?.response_text ??
    "I was unable to complete this task.";
  const sanitizedFallback = sanitizeOutput(rawFallback);
  const { evidence, receipts } = buildEvidence(task.steps);
  await finishTask(task, "completed", deps);
  return {
    type: "response",
    text: sanitizedFallback.text,
    language: lastPayload?.final_output?.language ?? "en",
    payload: lastPayload!,
    evidence: evidence.length > 0 ? evidence : undefined,
    receipts: receipts.length > 0 ? receipts : undefined,
    responseFormat: extractResponseFormat(lastPayload),
  };
}

// ─── Helpers ─────────────────────────────────────────────────

function createNewTask(sessionId: string): TaskState {
  return {
    taskId: `task-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    sessionId,
    status: "running",
    plan: null,
    steps: [],
    totalCostUsd: 0,
    startedAt: new Date().toISOString(),
    completedAt: null,
    error: null,
  };
}

function recordStep(
  state: RunState,
  action: string,
  toolName: string | null,
  toolParams: Record<string, unknown> | null,
  toolResult: ToolResult | null,
  confidence: number,
  reasoning: string,
  latencyMs: number,
): StepResult {
  const step: StepResult = {
    iteration: state.iteration,
    action,
    toolName,
    toolParams,
    toolResult,
    confidence,
    reasoning,
    costUsd: 0,
    latencyMs,
    timestamp: new Date().toISOString(),
  };
  state.recentSteps.push(step);
  // Keep only last 10 steps in memory
  if (state.recentSteps.length > 10) {
    state.recentSteps = state.recentSteps.slice(-10);
  }
  return step;
}

/**
 * Build evidence chain and action receipts from completed steps.
 * Evidence = internal observability. Receipts = customer-visible confirmations.
 */
function buildEvidence(steps: StepResult[]): {
  evidence: ResponseEvidence[];
  receipts: ActionReceipt[];
} {
  const evidence: ResponseEvidence[] = [];
  const receipts: ActionReceipt[] = [];

  for (const step of steps) {
    if (step.toolName && step.toolResult) {
      evidence.push({
        toolName: step.toolName,
        toolParams: step.toolParams ?? {},
        toolResult: step.toolResult.result as Record<string, unknown>,
        costUsd: step.costUsd,
        latencyMs: step.latencyMs,
        timestamp: step.timestamp,
      });

      // Generate receipts for successful tool calls
      if (step.toolResult.status === "ok") {
        receipts.push({
          action: step.toolName,
          reference: `${step.toolName}-${step.iteration}`,
          summary: step.reasoning || `Executed ${step.toolName}`,
          timestamp: step.timestamp,
        });
      }
    }
  }

  return { evidence, receipts };
}

async function finishTask(
  task: TaskState,
  status: TaskState["status"],
  deps: LoopDeps,
  error?: string,
): Promise<void> {
  task.status = status;
  task.completedAt = new Date().toISOString();
  if (error) {
    task.error = error;
  }
  // Save the full in-memory task directly — no need for updateTaskStatus()
  // to do an extra getTask() read-modify-write cycle.
  await deps.memory.saveTask(task);
}

/**
 * Extract structured response format from brain payload.
 * The brain may include response_format in generation output for rich rendering.
 */
function extractResponseFormat(
  payload: BrainPayload | undefined,
): ResponseFormat | undefined {
  if (!payload?.generation?.response_format) return undefined;
  const fmt = payload.generation.response_format;
  if (
    !fmt.type ||
    !["text", "list", "buttons", "carousel", "confirmation"].includes(fmt.type)
  ) {
    return undefined;
  }
  return fmt;
}
